The target was to extract the important data rather than focusing to ip details and port detials.<br>
In that case since multiple datasets having for each class, for the effectiveness of process and handling data, a data set was created using one pcap for each attack type.

### 1. Merge amd Build a Dataset from Extracted Data

In [26]:
import pandas as pd

# Import one benign data set
df1 = pd.read_csv("new_csv_output/benign.csv")
df1.head(5)

,pcap_file,timestamp,packet_length,src_mac,dst_mac,eth_type,src_ip,dst_ip,ip_version,ttl,...,syn,ack_flag,fin,rst,psh,urg,udp_length,icmp_type,icmp_code,payload_size
0,benign.pcap,1.751371e+09,640,NaN,NaN,NaN,192.168.0.1,192.168.0.1,4.0,64.0,...,0,0,0,0,0,0,NaN,NaN,NaN,624
1,benign.pcap,1.751371e+09,640,NaN,NaN,NaN,192.168.0.1,192.168.0.1,4.0,64.0,...,0,0,0,0,0,0,NaN,NaN,NaN,624
2,benign.pcap,1.751371e+09,64,NaN,NaN,NaN,192.168.0.1,192.168.0.1,4.0,64.0,...,0,0,0,0,0,0,NaN,NaN,NaN,48
3,benign.pcap,1.751371e+09,1856,NaN,NaN,NaN,192.168.0.3,192.168.0.1,4.0,64.0,...,0,0,0,0,0,0,NaN,NaN,NaN,1840
4,benign.pcap,1.751371e+09,64,NaN,NaN,NaN,192.168.0.1,192.168.0.3,4.0,64.0,...,0,0,0,0,0,0,NaN,NaN,NaN,48

In [27]:
print(df1.shape)

(140319, 31)

In [28]:
# Import one bruteforce data set
df2 = pd.read_csv("new_csv_output/ssh_medusa.csv")
df2.head(5)

,pcap_file,timestamp,packet_length,src_mac,dst_mac,eth_type,src_ip,dst_ip,ip_version,ttl,...,syn,ack_flag,fin,rst,psh,urg,udp_length,icmp_type,icmp_code,payload_size
0,BruteForce\BruteForce\Higher_Layer\ssh_medusa....,1.751025e+09,191,NaN,NaN,NaN,192.168.0.3,192.168.0.1,4.0,64.0,...,0,0,0,0,0,0,155.0,NaN,NaN,175
1,BruteForce\BruteForce\Higher_Layer\ssh_medusa....,1.751025e+09,196,NaN,NaN,NaN,172.31.0.1,172.31.0.134,4.0,64.0,...,0,0,0,0,0,0,160.0,NaN,NaN,180
2,BruteForce\BruteForce\Higher_Layer\ssh_medusa....,1.751025e+09,196,NaN,NaN,NaN,172.31.0.1,172.31.0.134,4.0,64.0,...,0,0,0,0,0,0,160.0,NaN,NaN,180
3,BruteForce\BruteForce\Higher_Layer\ssh_medusa....,1.751025e+09,152,NaN,NaN,NaN,172.31.0.134,192.168.0.10,4.0,62.0,...,0,1,0,0,1,0,NaN,NaN,NaN,136
4,BruteForce\BruteForce\Higher_Layer\ssh_medusa....,1.751025e+09,152,NaN,NaN,NaN,172.31.0.134,192.168.0.10,4.0,62.0,...,0,1,0,0,1,0,NaN,NaN,NaN,136

In [29]:
print(df2.shape)

(3314547, 31)

In [30]:
# Import one ddos data set
df3 = pd.read_csv("new_csv_output/ddos_icmp_hping3.csv")
df3.head(5)

,pcap_file,timestamp,packet_length,src_mac,dst_mac,eth_type,src_ip,dst_ip,ip_version,ttl,...,syn,ack_flag,fin,rst,psh,urg,udp_length,icmp_type,icmp_code,payload_size
0,ddos_icmp_hping3.pcap,1.751373e+09,1208,NaN,NaN,NaN,192.168.0.3,192.168.0.1,4.0,64.0,...,0,0,0,0,0,0,NaN,NaN,NaN,1192
1,ddos_icmp_hping3.pcap,1.751373e+09,1208,NaN,NaN,NaN,192.168.0.1,192.168.0.1,4.0,64.0,...,0,0,0,0,0,0,NaN,NaN,NaN,1192
2,ddos_icmp_hping3.pcap,1.751373e+09,64,NaN,NaN,NaN,192.168.0.1,192.168.0.1,4.0,64.0,...,0,0,0,0,0,0,NaN,NaN,NaN,48
3,ddos_icmp_hping3.pcap,1.751373e+09,448,NaN,NaN,NaN,192.168.0.1,192.168.0.1,4.0,64.0,...,0,0,0,0,0,0,NaN,NaN,NaN,432
4,ddos_icmp_hping3.pcap,1.751373e+09,64,NaN,NaN,NaN,192.168.0.1,192.168.0.1,4.0,64.0,...,0,0,0,0,0,0,NaN,NaN,NaN,48

In [31]:
# Import one dos data set
df4 = pd.read_csv("new_csv_output/icmp_hping3.csv")
df4.head(5)

,pcap_file,timestamp,packet_length,src_mac,dst_mac,eth_type,src_ip,dst_ip,ip_version,ttl,...,syn,ack_flag,fin,rst,psh,urg,udp_length,icmp_type,icmp_code,payload_size
0,icmp_hping3.pcap,1.750672e+09,1083,NaN,NaN,NaN,192.168.0.3,192.168.0.1,4.0,64.0,...,0,0,0,0,0,0,1047.0,NaN,NaN,1067
1,icmp_hping3.pcap,1.750672e+09,1083,NaN,NaN,NaN,192.168.0.3,192.168.0.1,4.0,64.0,...,0,0,0,0,0,0,1047.0,NaN,NaN,1067
2,icmp_hping3.pcap,1.750672e+09,1083,NaN,NaN,NaN,192.168.0.3,192.168.0.1,4.0,64.0,...,0,0,0,0,0,0,1047.0,NaN,NaN,1067
3,icmp_hping3.pcap,1.750672e+09,1083,NaN,NaN,NaN,192.168.0.3,192.168.0.1,4.0,64.0,...,0,0,0,0,0,0,1047.0,NaN,NaN,1067
4,icmp_hping3.pcap,1.750672e+09,1083,NaN,NaN,NaN,192.168.0.3,192.168.0.1,4.0,64.0,...,0,0,0,0,0,0,1047.0,NaN,NaN,1067

In [32]:
dfs = {
    "df1": df1,
    "df2": df2,
    "df3": df3,
    "df4": df4
}

reference = list(df1.columns)

for name, df in dfs.items():
    if list(df.columns) == reference:
        print(f"{name}: Columns match")
    else:
        print(f"{name}: Columns do NOT match")

df1: Columns match
df2: Columns match
df3: Columns match
df4: Columns match

In [33]:
import pandas as pd

# Add Attack Type column
df1["Attack Type"] = "Benign"
df2["Attack Type"] = "DDoS"
df3["Attack Type"] = "DOS"
df4["Attack Type"] = "Bruteforce"

# Merge all DataFrames
merged_df = pd.concat(
    [df1, df2, df3, df4],
    ignore_index=True
)

# Save to CSV
merged_df.to_csv("merged_dataset.csv", index=False)

# Check the result
print("Merged dataset shape:", merged_df.shape)
print("\nAttack Type counts:")
print(merged_df["Attack Type"].value_counts())

Merged dataset shape: (4648559, 32)

Attack Type counts:
Attack Type
DDoS          3314547
Bruteforce     784241
DOS            409452
Benign         140319
Name: count, dtype: int64

In [34]:
merged_df.to_csv('merged_dataset.csv', index=False)

pcap_file             0
timestamp             0
packet_length         0
src_mac          140319
dst_mac          140319
eth_type         140319
src_ip              319
dst_ip              319
ip_version          319
ttl                 319
ip_length           319
tos                 319
id                  319
flags_ip            319
fragment            319
protocol            319
src_port          84465
dst_port          84465
seq               84465
ack               84465
window            84465
syn                   0
ack_flag              0
fin                   0
rst                   0
psh                   0
urg                   0
udp_length       115517
icmp_type        139371
icmp_code        139371
payload_size          0
dtype: int64

In [7]:
# TCP packets with missing ports
tcp_missing = df1[(df1["protocol"] == 6) &
                 (df1["src_port"].isna() | df1["dst_port"].isna())]

print("TCP packets missing ports:", len(tcp_missing))

# UDP packets missing UDP length
udp_missing = df1[(df1["protocol"] == 17) &
                 (df1["udp_length"].isna())]

print("UDP packets missing udp_length:", len(udp_missing))

# ICMP packets missing type/code
icmp_missing = df1[(df1["protocol"] == 1) &
                  (df1["icmp_type"].isna() | df1["icmp_code"].isna())]

print("ICMP packets missing fields:", len(icmp_missing))

TCP packets missing ports: 0
UDP packets missing udp_length: 0
ICMP packets missing fields: 0

#### Fill structural missing values

Instead of deleting columns or rows, replace them with a sentinel value.

In [8]:
numeric_cols = [
    "src_port",
    "dst_port",
    "seq",
    "ack",
    "window",
    "udp_length",
    "icmp_type",
    "icmp_code"
]

df1[numeric_cols] = df1[numeric_cols].fillna(-1)

In [9]:
categorical_cols = [
    "src_mac",
    "dst_mac",
    "eth_type"
]

df1[categorical_cols] = df1[categorical_cols].fillna("Unknown")

In [10]:
df1["is_tcp"] = (df1["protocol"] == 6).astype(int)
df1["is_udp"] = (df1["protocol"] == 17).astype(int)
df1["is_icmp"] = (df1["protocol"] == 1).astype(int)

#### Check Data Types

In [14]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 140319 entries, 0 to 140318
Data columns (total 34 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   pcap_file      140319 non-null  str
 1   timestamp      140319 non-null  float64
 2   packet_length  140319 non-null  int64
 3   src_mac        140319 non-null  object
 4   dst_mac        140319 non-null  object
 5   eth_type       140319 non-null  object
 6   src_ip         140000 non-null  str
 7   dst_ip         140000 non-null  str
 8   ip_version     140000 non-null  float64
 9   ttl            140000 non-null  float64
 10  ip_length      140000 non-null  float64
 11  tos            140000 non-null  float64
 12  id             140000 non-null  float64
 13  flags_ip       140000 non-null  float64
 14  fragment       140000 non-null  float64
 15  protocol       140000 non-null  float64
 16  src_port       140319 non-null  float64
 17  dst_port       140319 non-null  float64
 18  seq            140319 non-null  float64
 19  ack            140319 non-null  float64
 20  window         140319 non-null  float64
 21  syn            140319 non-null  int64
 22  ack_flag       140319 non-null  int64
 23  fin            140319 non-null  int64
 24  rst            140319 non-null  int64
 25  psh            140319 non-null  int64
 26  urg            140319 non-null  int64
 27  udp_length     140319 non-null  float64
 28  icmp_type      140319 non-null  float64
 29  icmp_code      140319 non-null  float64
 30  payload_size   140319 non-null  int64
 31  is_tcp         140319 non-null  int64
 32  is_udp         140319 non-null  int64
 33  is_icmp        140319 non-null  int64
dtypes: float64(17), int64(11), object(3), str(3)
memory usage: 36.4+ MB

In [15]:
categorical_features = [
    'src_mac',
    'dst_mac',
    'eth_type',
    'src_ip',
    'dst_ip'
]

In [16]:
numerical_features = [
    'timestamp',
    'packet_length',
    'ip_version',
    'ttl',
    'ip_length',
    'tos',
    'id',
    'flags_ip',
    'fragment',
    'protocol',
    'src_port',
    'dst_port',
    'seq',
    'ack',
    'window',
    'udp_length',
    'icmp_type',
    'icmp_code',
    'payload_size'
]

In [17]:
binary_features = [
    'syn',
    'ack_flag',
    'fin',
    'rst',
    'psh',
    'urg',
    'is_tcp',
    'is_udp',
    'is_icmp'
]

In [18]:
# Drop identifiers
df1 = df1.drop(columns=[
    'pcap_file',
    'timestamp',
    'src_ip',
    'dst_ip',
    'src_mac',
    'dst_mac'
], errors='ignore')